import React from 'react';
import { Header } from '../../Core/Components';
export const Home: React.FC = () => {
  return (
    <div>
      <Header></Header>
      <h1>Home Page</h1>
      <p>Hola soy gabo y me gusta el pene peludo peludo peludo peludo peludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludo peludo peludo peludo peludo peludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludo peludo peludo peludo peludo peludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludo peludo peludo peludo peludo peludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludo peludo peludo peludo peludo peludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludo peludo peludo peludo peludo peludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludo peludo peludo peludo peludo peludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludo peludo peludo peludo peludo peludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludo peludo peludo peludo peludo peludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludo peludo peludo peludo peludo peludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludopeludo peludo peludo peludo </p>
    </div>

  );
};
